# This is a basic workflow to help you get started with Actions

name: Make plot

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
  repository_dispatch:
  schedule:
    - cron:  '*/5 * * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        
      - name: Setup python
        uses: actions/setup-python@v2
        
      - name: Treebeard Jupyter Notebook CI
        # You may pin to the exact commit or the version.
        # uses: treebeardtech/treebeard@b4ae75bdd1a2137d971f28f35139db47642d3cda
        uses: treebeardtech/treebeard@v0.1.1
        with:
          # notebooks to run
          notebooks: "LA_County_Triggers.ipynb"
      
      - name: Commit and push if it changed
        run: |-
          ls
          pwd
          git config --global user.email "graph-bot@example.com"
          git config --global user.name "GRAPH-bot"
          git rm plots/graph.png
          git add plots/graph.png && git commit -m "Updated graph"
          git push
